version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mailtrain
      - MYSQL_DATABASE=mailtrain
      - MYSQL_USER=mailtrain
      - MYSQL_PASSWORD=mailtrain
  redis:
    image: redis:3.0

  mailtrain:
    build: ./
    # volumes:
      # - ./:/app
    ports:
      - "3000:3000"
    restart: always